# Generated by Django 6.0.3 on 2026-04-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_qrcodes/'),
        ),
    ]
