# Generated by Django 5.0.4 on 2026-04-23 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_qr_code_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Tashkilot', 'verbose_name_plural': 'Tashkilotlar'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='dynamic_qr_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('kk', 'Qaraqalpaq'), ('uz', "O'zbek"), ('ru', 'Rus')], default='kk', max_length=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Sinf/Sinfxon',
                'verbose_name_plural': 'Sinf/Sinfxonlar',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.schoolclass'),
        ),
    ]
