# Generated by Django 5.0.4 on 2026-04-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plain_password',
            field=models.CharField(blank=True, help_text="Adminlar ko'rishi uchun vaqtinchalik saqlanadigan parol", max_length=128, null=True),
        ),
    ]
