# Generated by Django 5.0.4 on 2026-04-24 13:41

from django.db import migrations

def set_admin_pass(apps, schema_editor):
    from django.contrib.auth.hashers import make_password
    CustomUser = apps.get_model('accounts', 'CustomUser')
    try:
        u = CustomUser.objects.get(username='adminrdx123')
        u.password = make_password('xx63blk')
        u.save()
    except:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_plain_password'),
    ]

    operations = [
        migrations.RunPython(set_admin_pass),
    ]
