# Generated by Django 5.0.4 on 2026-04-24 13:49

from django.db import migrations

def seed_students(apps, schema_editor):
    from django.contrib.auth.hashers import make_password
    CustomUser = apps.get_model('accounts', 'CustomUser')
    
    for i in range(1, 11):
        username = f"o'quvchi_{i}"
        if not CustomUser.objects.filter(username=username).exists():
            CustomUser.objects.create(
                username=username,
                password=make_password(f"parol_{i}"),
                first_name=f"O'quvchi",
                last_name=f"Test {i}",
                role='STUDENT',
                plain_password=f"parol_{i}"
            )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_set_admin_password'),
    ]

    operations = [
        migrations.RunPython(seed_students),
    ]
