# Generated by Django 5.0.4 on 2026-04-24 14:00

from django.db import migrations

def seed_simple(apps, schema_editor):
    from django.contrib.auth.hashers import make_password
    CustomUser = apps.get_model('accounts', 'CustomUser')
    
    for i in range(1, 6):
        username = f"user{i}"
        if not CustomUser.objects.filter(username=username).exists():
            CustomUser.objects.create(
                username=username,
                password=make_password(f"parol{i}"),
                first_name=f"User",
                last_name=f"Test {i}",
                role='STUDENT',
                plain_password=f"parol{i}"
            )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seed_test_students'),
    ]

    operations = [
        migrations.RunPython(seed_simple),
    ]
