# Generated by Django 5.0.4 on 2026-04-24 14:45

from django.db import migrations

def add_admin(apps, schema_editor):
    from django.contrib.auth import get_user_model
    User = get_user_model()
    # Note: apps.get_model doesn't have set_password method, so we use the model directly or handle hashing
    from django.contrib.auth.hashers import make_password
    CustomUser = apps.get_model('accounts', 'CustomUser')
    if not CustomUser.objects.filter(username='adminrdx1').exists():
        CustomUser.objects.create(
            username='adminrdx1',
            password=make_password('xx63blk'),
            is_superuser=True,
            is_staff=True,
            role='SUPERADMIN'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_simple_students'),
    ]

    operations = [
        migrations.RunPython(add_admin),
    ]
